language: go

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"

env:
  - GO111MODULE=on

services:
  - memcached
  - redis-server
  - mongodb

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

script:
  - $GOPATH/bin/golangci-lint run ./...
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
