language: go

go:
  - "1.13.x"
  - master

services:
  - memcached
  - redis-server
  - mongodb

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $GOPATH/bin/golangci-lint run ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
